This is makeindex, version 2.15 [TeX Live 2018] (kpathsea + Thai support).
Scanning style file ./TFG-TFM_EPS_UA.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file TFG-TFM_EPS_UA.acn....done (65 entries accepted, 0 rejected).
Sorting entries....done (423 comparisons).
Generating output file TFG-TFM_EPS_UA.acr....done (67 lines written, 0 warnings).
Output written in TFG-TFM_EPS_UA.acr.
Transcript written in TFG-TFM_EPS_UA.alg.
